name: ananta_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # HTTP client for REST APIs
  dio: ^5.5.0

  # Store tokens (e.g., guard JWT) securely
  flutter_secure_storage: ^9.2.2

  # QR scanner for guest flows (optional; remove if not needed)
  qr_code_scanner_plus: ^2.0.0

  # Optional: Typed API clients and JSON models
  retrofit: ^4.0.3
  json_annotation: ^4.9.0

  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation for Retrofit/JSON (only needed if using them)
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/logo.png
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
