// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3oYrofclZG9yE0IqGkBvqp2alqZs9vXQ',
    appId: '1:210121266442:web:7755f3931b680b597316f3',
    messagingSenderId: '210121266442',
    projectId: 'fcm-notification-386b8',
    authDomain: 'fcm-notification-386b8.firebaseapp.com',
    storageBucket: 'fcm-notification-386b8.firebasestorage.app',
    measurementId: 'G-BDWGGGJ41B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt4xuvnbxEiGgkoPOTyE0P54T3ncGtuxY',
    appId: '1:210121266442:android:7571be5fce1934fd7316f3',
    messagingSenderId: '210121266442',
    projectId: 'fcm-notification-386b8',
    storageBucket: 'fcm-notification-386b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLrlVXdzeYGR0Go4OGedt-5euY9SZH_Ow',
    appId: '1:210121266442:ios:a85eb88f3e0b18207316f3',
    messagingSenderId: '210121266442',
    projectId: 'fcm-notification-386b8',
    storageBucket: 'fcm-notification-386b8.firebasestorage.app',
    iosBundleId: 'com.example.anantaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLrlVXdzeYGR0Go4OGedt-5euY9SZH_Ow',
    appId: '1:210121266442:ios:a85eb88f3e0b18207316f3',
    messagingSenderId: '210121266442',
    projectId: 'fcm-notification-386b8',
    storageBucket: 'fcm-notification-386b8.firebasestorage.app',
    iosBundleId: 'com.example.anantaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3oYrofclZG9yE0IqGkBvqp2alqZs9vXQ',
    appId: '1:210121266442:web:26f10346d9d728ea7316f3',
    messagingSenderId: '210121266442',
    projectId: 'fcm-notification-386b8',
    authDomain: 'fcm-notification-386b8.firebaseapp.com',
    storageBucket: 'fcm-notification-386b8.firebasestorage.app',
    measurementId: 'G-YK9E26685L',
  );
}
