import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import 'core/navigation_service.dart';
import 'models/login_type.dart';
import 'screens/send_otp_page.dart';
import 'screens/visitor_list.dart';
import 'screens/visitor_qr.dart';
import 'screens/visitor_manual_entry.dart';
import 'screens/home_shell.dart';
import 'firebase_options.dart'; // generated by flutterfire CLI

/// Background handler for FCM messages
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  print('Background message received: ${message.messageId}');
  _showNotification(message);
}

/// Local notification plugin
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

/// Helper to show local notification
Future<void> _showNotification(RemoteMessage message) async {
  final notification = message.notification;
  final android = notification?.android;

  if (notification != null && android != null) {
    const AndroidNotificationDetails androidDetails = AndroidNotificationDetails(
      'ananta_channel', // channel id
      'Ananta Notifications', // channel name
      channelDescription: 'Channel for Ananta app notifications',
      importance: Importance.max,
      priority: Priority.high,
    );

    const NotificationDetails platformDetails =
        NotificationDetails(android: androidDetails);

    await flutterLocalNotificationsPlugin.show(
      notification.hashCode,
      notification.title ?? 'Ananta',
      notification.body ?? '',
      platformDetails,
    );
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize local notifications
  const AndroidInitializationSettings androidInitSettings =
      AndroidInitializationSettings('@mipmap/ic_launcher');

  const InitializationSettings initSettings =
      InitializationSettings(android: androidInitSettings);

  await flutterLocalNotificationsPlugin.initialize(initSettings);

  // Set background message handler
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(const AnantaApp());
}

class AnantaApp extends StatelessWidget {
  const AnantaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ananta',
      debugShowCheckedModeBanner: false,
      navigatorKey: NavigationService.navigatorKey,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.indigo),
      ),
      initialRoute: '/send-otp',
      routes: {
        '/send-otp': (_) => const SendOtpPage(),
        '/visitorList': (_) => const VisitorListPage(loginType: LoginType.guard),
        '/generateQr': (_) => const GenerateQrPage(),
        '/manualEntry': (_) => const ManualEntryPage(),
        '/home': (_) => const HomeLoader(),
      },
    );
  }
}

/// Loader widget to decide correct HomeShell role
class HomeLoader extends StatefulWidget {
  const HomeLoader({super.key});

  @override
  State<HomeLoader> createState() => _HomeLoaderState();
}

class _HomeLoaderState extends State<HomeLoader> {
  final _secure = const FlutterSecureStorage();
  String? _role;
  LoginType? _loginType;
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _loadUser();
    _setupFCM();
  }

  Future<void> _loadUser() async {
    final role = await _secure.read(key: 'user_role');
    final loginTypeStr = await _secure.read(key: 'login_type');

    setState(() {
      _role = role ?? 'ROLE_GUARD';
      _loginType = loginTypeStr == 'residence' ? LoginType.residence : LoginType.guard;
      _loading = false;
    });
  }

  /// Configure FCM + Local Notifications
  Future<void> _setupFCM() async {
    final messaging = FirebaseMessaging.instance;

    // Request permissions
    NotificationSettings settings = await messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );

    if (settings.authorizationStatus == AuthorizationStatus.authorized) {
      print('User granted permission for notifications');
    }

    // Get FCM token
    final token = await messaging.getToken();
    print('✅ FCM Token: $token'); // use in Postman to send test notification

    // Foreground notifications
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print('Foreground message: ${message.notification?.title}');
      _showNotification(message);
    });

    // Notification click handler
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('Notification clicked: ${message.notification?.title}');
      // TODO: navigate to screen if needed, e.g. NavigationService.navigatorKey.currentState?.pushNamed("/visitorList");
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return const Scaffold(
        body: Center(child: CircularProgressIndicator()),
      );
    }
    return HomeShell(
      loginType: _loginType ?? LoginType.guard,
      role: _role ?? 'ROLE_GUARD',
    );
  }
}
